# Generated by Django 3.0.3 on 2020-03-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respiratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('_id', models.CharField(max_length=50)),
                ('instalacion_notifica', models.CharField(max_length=100)),
                ('tipo_paciente', models.CharField(choices=[('A', 'Ambutorio'), ('H', 'Hospitalizado')], max_length=1)),
                ('tipo_identificacion', models.CharField(choices=[('C', 'Cédula'), ('P', 'Pasaporte'), ('E', 'Expediente')], max_length=1)),
                ('muestra_1_tipo', models.CharField(choices=[('ANF', 'Aspirado naso faríngeo'), ('BRQ', 'Bronquios'), ('HF', 'Hisopado Faríngeo'), ('HN', 'Hisopado Nasal'), ('HNF', 'Hisopado Nasofaringeo'), ('LVA', 'Lavado Broncoalveolar'), ('LCF', 'Liquido Cefalorraquideo'), ('LPL', 'Liquido Pleural'), ('PLM', 'Pulmón'), ('SAN', 'Sangre'), ('TEJ', 'Tejido'), ('TRA', 'Tráquea')], max_length=3)),
                ('muestra_1_toma', models.DateTimeField(auto_now_add=True)),
                ('muestra_1_envio', models.DateTimeField(auto_now=True, null=True)),
                ('muestra_1_recibido', models.DateTimeField(auto_now=True, null=True)),
                ('muestra_2_tipo', models.CharField(blank=True, choices=[('ANF', 'Aspirado naso faríngeo'), ('BRQ', 'Bronquios'), ('HF', 'Hisopado Faríngeo'), ('HN', 'Hisopado Nasal'), ('HNF', 'Hisopado Nasofaringeo'), ('LVA', 'Lavado Broncoalveolar'), ('LCF', 'Liquido Cefalorraquideo'), ('LPL', 'Liquido Pleural'), ('PLM', 'Pulmón'), ('SAN', 'Sangre'), ('TEJ', 'Tejido'), ('TRA', 'Tráquea')], max_length=3, null=True)),
                ('muestra_2_toma', models.DateTimeField(auto_now_add=True, null=True)),
                ('muestra_2_envio', models.DateTimeField(auto_now=True, null=True)),
                ('muestra_2_recibido', models.DateTimeField(auto_now=True, null=True)),
                ('muestra_3_tipo', models.CharField(blank=True, choices=[('ANF', 'Aspirado naso faríngeo'), ('BRQ', 'Bronquios'), ('HF', 'Hisopado Faríngeo'), ('HN', 'Hisopado Nasal'), ('HNF', 'Hisopado Nasofaringeo'), ('LVA', 'Lavado Broncoalveolar'), ('LCF', 'Liquido Cefalorraquideo'), ('LPL', 'Liquido Pleural'), ('PLM', 'Pulmón'), ('SAN', 'Sangre'), ('TEJ', 'Tejido'), ('TRA', 'Tráquea')], max_length=3, null=True)),
                ('muestra_3_toma', models.DateTimeField(auto_now_add=True, null=True)),
                ('muestra_3_envio', models.DateTimeField(auto_now=True, null=True)),
                ('muestra_3_recibido', models.DateTimeField(auto_now=True, null=True)),
                ('muestra_4_tipo', models.CharField(blank=True, choices=[('ANF', 'Aspirado naso faríngeo'), ('BRQ', 'Bronquios'), ('HF', 'Hisopado Faríngeo'), ('HN', 'Hisopado Nasal'), ('HNF', 'Hisopado Nasofaringeo'), ('LVA', 'Lavado Broncoalveolar'), ('LCF', 'Liquido Cefalorraquideo'), ('LPL', 'Liquido Pleural'), ('PLM', 'Pulmón'), ('SAN', 'Sangre'), ('TEJ', 'Tejido'), ('TRA', 'Tráquea')], max_length=3, null=True)),
                ('muestra_4_toma', models.DateTimeField(auto_now_add=True, null=True)),
                ('muestra_4_envio', models.DateTimeField(auto_now=True, null=True)),
                ('muestra_4_recibido', models.DateTimeField(auto_now=True, null=True)),
                ('muestra_5_tipo', models.CharField(blank=True, choices=[('ANF', 'Aspirado naso faríngeo'), ('BRQ', 'Bronquios'), ('HF', 'Hisopado Faríngeo'), ('HN', 'Hisopado Nasal'), ('HNF', 'Hisopado Nasofaringeo'), ('LVA', 'Lavado Broncoalveolar'), ('LCF', 'Liquido Cefalorraquideo'), ('LPL', 'Liquido Pleural'), ('PLM', 'Pulmón'), ('SAN', 'Sangre'), ('TEJ', 'Tejido'), ('TRA', 'Tráquea')], max_length=3, null=True)),
                ('muestra_5_toma', models.DateTimeField(auto_now_add=True, null=True)),
                ('muestra_5_envio', models.DateTimeField(auto_now=True, null=True)),
                ('muestra_5_recibido', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
