# Generated by Django 3.0.3 on 2020-03-15 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respiratorio',
            name='Dx_ICD10',
            field=models.CharField(default='JXYZ', max_length=5),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='Embarazo',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='aislamiento',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='alergia',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='contacto_confirmado',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='corresponde_vacuna',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(2020, 3, 15)),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='hipertension',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='inmunosupresion',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='nombre_contacto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='obesidad',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='otras',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='porta_tarjeta',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='riesgo_profesional',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'Masculino'), (0, 'Femenino')], default=1),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='tabaquismo',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='tipo_contacto',
            field=models.CharField(choices=[('F', 'Familiar'), ('L', 'Laboral'), ('E', 'Escolar'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='tipo_riesgo_profesional',
            field=models.CharField(choices=[('T', 'Trabajador Agropecuario'), ('S', 'Trabajador de Salud'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='respiratorio',
            name='viaje_15_dias',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
    ]
