# Generated by Django 3.0.3 on 2020-03-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_auto_20200315_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respiratorio',
            name='Embarazo',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No'), (2, 'Desconocido'), (3, 'No aplica')], default=3),
        ),
    ]
